# Generated by Django 3.1.7 on 2021-03-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='weight',
            field=models.FloatField(),
        ),
    ]
